---
jobs:
  - name: build-artifact
    plan:
    - get: git-repo
      public: true
      trigger: true
    - task: build-artifact
      file: git-repo/feedback_form/ci/tasks/build-artifact.yml


  - name: deploy-app
    plan:
    - get: git-repo
      passed: [build-artifact]
      trigger: true
    - put: deploy-app
      params:
        manifest: git-repo/feedback_form/manifest.yml
        path: git-repo/feedback_form/target/demo-web-app-0.0.1-SNAPSHOT.jar
        CF_TRACE: true


resources:
- name: git-repo
  type: git
  source:
    uri: {{GIT_REPO}}
    branch: {{GIT_BRANCH}}
    private_key: {{GIT_PRIVATE_KEY}}

- name: deploy-app
  type: cf
  source:
    api: {{CF_API}}
    username: {{CF_USER}}
    password: {{CF_PASS}}
    organization: {{CF_ORG}}
    space: {{CF_SPACE}}
    skip_cert_check: true
