---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'


inputs:
  - name: git-repo

outputs:
  - name: build-output

run:
  path: git-repo/feedback_form/ci/tasks/build.sh
