---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: "latest"


inputs:
  - name: git-repo
#
# outputs:
#   - name: artifact-dir

run:
  path: git-repo/feedback_form/ci/tasks/build-artifact.sh
